# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Julio Trigo
description: > # this means to ignore newlines until "baseurl:"
  ["Software engineer", "Scrum master (CSM)", "Python developer", "Team lead"]
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.juliotrigo.com" # the base hostname & protocol for your site, e.g. http://example.com

desktop_website: "http://desktop.juliotrigo.com"

webmentions:
  username: www.juliotrigo.com

twitter_username: juliotrigo
github_username: juliotrigo
slides_username: juliotrigo
pypi_username: juliotrigo

gravatar:
  photo_url: https://www.gravatar.com/avatar/380bab69599e9aa6c03e3fce2bb79a75
  photo_title: Julio Trigo's photo

logo_title: Julio Trigo's logo

author: Julio Trigo

show_excerpts: true # set to true to show excerpts on the homepage
excerpt_separator: "<!--more-->"
excerpt_link_text: ...read more

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

copyright: Copyright © 2013-2020 Julio Vicente Trigo Guijarro
license_link_text: License &amp; copyright
powered_by: >
  Powered by <a href="https://pages.github.com/">GitHub Pages</a>
  and <a href="https://jekyllrb.com/">Jekyll</a>
  using a customized <a href="https://github.com/jekyll/minima">Minima</a> theme

header_pages:
  - about.md
  - articles.md
  - bookmarks.md
  - books.md
  - projects.md
  - presentations.md

timezone: Europe/London

google_analytics: UA-104164449-1

google_font:
  - url: https://fonts.googleapis.com/css?family=Indie+Flower&display=swap
  - url: https://fonts.googleapis.com/css?family=Ubuntu+Mono&display=swap
  - url: https://fonts.googleapis.com/css?family=Material+Icons&display=swap

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
